version: 2

sources:
  - name: raw
    schema: gwz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to orders table (ship in this case)
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: amount paid by customer
          - name: quantity
            description: number of products purchased per order
      - name: product
        identifier: raw_gz_product
        description: products of greenweez
        columns:
          - name: products_id
            description: PK
            tests:
              - unique
              - not_null
          - name: purchse_price
            description: purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: shipping data for the orders
        columns:
          - name: orders_id
            description: PK
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: price paid by customer for shipping
          - name: log_cost
            description: cost of parcel prep
          - name: ship_cost
            description: shipping cost paid
